### ISSUE TITLE
fusion selection

### ISSUE THREAD

**Issue by gybeata** [matq007/fusion-report#14]
Thank you for this stand-alone report creator it is very useful.
I have a question regarding the fusions that are reported as a separate .html. Why those? How are they selected? I have got a list of 9 .html, but only 2 of them are reported in the index.html 
Also, what does the score mean in the last column of the table if index.html ?

Thank you

**Comment by matq007** [comment]
Hi, 

the summary report is generated by a tool called `fusion-report` which is hosted [here](https://github.com/matq007/fusion-report). We are using 3 databases currently: `FusionGDB`, `Mitelman` and `COSMIC`. In version `1.0.0` we are only gathering data from `FusionGDB`,  there is no info about the fusion a page will not be generated.
This will be changed in an upcoming version. I would like to retrieve more data also from Mitelman database but I first have to figure out all the relations between the tables in the database as there is no schema anywhere. 
The reason why we are using all 3 databases is that we estimate the final score from this. 
`Mitelman` database is based on clinical studies and `COSMIC` is really conservative. `FusionGDB` looks like a good database with rich information about the fusions.

The score defines how legitimate the fusion is. It is a weighted scoring, more info can be found [here](https://matq007.github.io/fusion-report/scoring.html).

Let me know if you have more questions 🙂
