### ISSUE TITLE
COSMIC fusion not detected

### ISSUE THREAD

**Issue by ChiBia** [matq007/fusion-report#19]
fusion-report correctly detects fusion present in Mitelman and in FusionGDB but not in COSMIC

**Comment by matq007** [comment]
Hi @ChiBia, do you have an example where it detected wrong? I am going through the database and it seems ok so far.

**Comment by ChiBia** [comment]
Hi Martin, I ran 130 samples so far, some of which are cancer cell lines with a lot of detected fusions and none where found in cosmic.
I forgot to mention that I'm using the singularity images, sorry

**Comment by matq007** [comment]
Thanks for the info. Just to make sure, are these fusions actually in COSMIC database? This database is quite limited.

**Comment by ChiBia** [comment]
I actually found one in a sample I ran lately! I didn't realize they were this rare, sorry I made you waste your time.

**Comment by matq007** [comment]
No problem, glad it got sorted out. There will be new version soon with new data from databases 🙂
