### ISSUE TITLE
Arriba in fusion-report vs. nf-core/rnafusion

### ISSUE THREAD

**Issue by suhrig** [matq007/fusion-report#24]
Hi Martin,

I see that you have added Arriba to the fusion-report repository. Many thanks for that! As far as I can see, the nf-core/rnafusion repository does not yet support the tool, however. Are there plans to add Arriba there as well? I might find some time to contribute to code development in a few weeks from now, in case you could use some help.

Regards,
Sebastian

**Comment by matq007** [comment]
Hi @suhrig, arriba is implemented already in `dev` branch. We are finalizing  the documentation for the new release: https://github.com/nf-core/rnafusion/pull/97. It's going to be out this week :)

**Comment by suhrig** [comment]
That's great news! Thanks again!
