### ISSUE TITLE
Exon Skipping Annotation

### ISSUE THREAD

**Issue by tefirman** [matq007/fusion-report#29]
Hello!

This might be a long shot, but any chance your software can annotate exon skipping events? They don't technically fit the true definition of a "fusion", but they have similar mechanics if you think of them as intragenic fusions... Just wanted to check. Thanks for your help!

-TF

**Comment by matq007** [comment]
Hi @tefirman, not sure about that. You will have to check all the individual tools in [rnafusion](https://github.com/nf-core/rnafusion). If the tool is able to detect it, we can implement it.
