### ISSUE TITLE
where is the database

### ISSUE THREAD

**Issue by chaoyanggu** [matq007/fusion-report#37]
I downloaded the install package ，and I want to use  the test data that comes with the software for testing; but I don’t know what the path of the database refers to,  I can not found a detailed description. How can I running the shell in tests?

test data:/software/fusion-report-master/tests/test_data/
data:/software/fusion-report-master/fusion_report/data/schema/ ?

thanks

**Comment by chaoyanggu** [comment]
fusion_report download
    --cosmic_usr '<username>'
    --cosmic_passwd '<password>'
    /path/to/db
whether the above codes can  download the data of three databases (FusionGDB, Mitelman, COSMIC), or it  only can download the data from COSMIC;

I download the data from the website  https://ccsm.uth.edu/FusionGDB/index.html; and
 sqlite3 fusiongdb.db < /software/fusion-report-master/fusion_report/data/schema//FusionGDB.sql

but it does not work; error :sqlite3.OperationalError: no such table: tcga_chitars_combined_fusion_information_on_hg19

**Comment by matq007** [comment]
Hi @chaoyanggu, the `fusion_report download` will download all datasets. You have to provide the credentials for COSMIC, as this is the only database that requires authentication. The process will download the databases to your specified path, you have to replace `/path/to/db` to your system for example `~/Desktop`.

Regarding the test data, you will have to download them from [repo](https://github.com/matq007/fusion-report/tree/master/tests/test_data) and then just specify the path the directory.

**Comment by chaoyanggu** [comment]
I registered a COSMIC  account for login , the user name is my email, and then I used the email and password to download the database,
the  codes is:
/software/fusion-report-master/bin/fusion_report download --cosmic_usr '<xxxx@ucl.ac.uk>' --cosmic_passwd '<password>' ./db/, 

but the following error occurred;
fusion_report.common.exceptions.app.AppException: HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
Found
HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
Found

is there any other way to download the data？
thanks

**Comment by matq007** [comment]
Hi, this seems like some kind of a network issue. Are you behind a proxy?
I've installed the tool over with conda and ran the download myself without any issue. Could try running it on your machine instead of server?

**Comment by matq007** [comment]
After experiencing this issue in nf-core/rnafusion, this is a firewall issue. The access to ftp is blocked, so if you have still issues with downloading you will have to install the package on your work notebook and then transfer the database to cluster.
