### ISSUE TITLE
Mitelman database migrated

### ISSUE THREAD

**Issue by prepiscak** [matq007/fusion-report#42]
Hi, 

First of all, thank you for the great tool!

It seems the Mitelman database moved to different location:
https://cgap.nci.nih.gov/cgap_mitelman_retire_notice.html

Therefore, the download command cannot download: ftp://ftp1.nci.nih.gov/pub/CGAP/mitelman.tar.gz

It should be possible to download the data from:
https://mitelmandatabase.isb-cgc.org/about

However, it looks like it contains different files to the original mitelman.tar.gz.

In the meantime: Is it possible to specify selected databases to run with fusion-report (i.e. ignoring Mitelman database?)

Cheers,

Peter

**Comment by matq007** [comment]
Thank you for info, I will try to update the tool as soon as possible. Unfortunately, the download is not option at the moment.
